name: Android CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: run ktlint
      run: ./gradlew ktlintCheck
    - name: run lint
      run: ./gradlew lintDebug
    - name: run detekt
      run: ./gradlew detekt
    - name: run tests
      run: ./gradlew testDebugUnitTest
    - name: run assemble
      run: ./gradlew assembleDebug
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: install bundler
      run: gem install bundler:2.1.2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: MeilCli/danger-action@v4
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
