name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    - name: Fetch tags
      run: git fetch origin 'refs/tags/*:refs/tags/*'
    - name: run assemble
      run: ./gradlew assemble
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Publish
      run: ./gradlew publish -PbintrayUser=${{ secrets.BINTRAY_USER_ID }} -PbintrayKey=${{ secrets.BINTRAY_API_KEY }} -PpublishVersion=${{ env.RELEASE_VERSION }}
